### ISSUE TITLE
How To Train and Test

### ISSUE THREAD

**Issue by blumonkey** [jlipps/hmm-tagger#1]
Hello,

I was looking for a HMM based POS tagger for a long time, and stubled across your repo. It looks simple although not much information has been provided as to how to use this tool. Can you give a few commands, to train a dataset, the input format, and testing on a sequence?

Thanks!

**Comment by jlipps** [comment]
Hi @blumonkey this was done as a class project and isn't really intended for others to use. While I guess it's possible you'll have to figure out how to adapt the code for your own purposes.
